# Generated by Django 4.1.3 on 2022-11-07 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_alter_site_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
    ]
