# Generated by Django 4.1.3 on 2022-11-08 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0006_hazard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hazard',
            old_name='polygon',
            new_name='point',
        ),
    ]
