# Generated by Django 4.1.3 on 2022-11-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0007_rename_polygon_hazard_point'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
